# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'currency-converter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for currency-converter
	pod "PromiseKit/CorePromise", "~> 6.8"
	pod 'SwiftyJSON', '~> 4.0'

end
